# .travis.yml
language: node_js
dist: xenial
sudo: required

cache:
  timeout: 600
  directories:
    - "node_modules"
    - "docker_cache"

matrix:
  fast_finish: true
  include:
    - node_js: "10"
    - node_js: "8"

install:
  - npm i

before_script:
  - bash scripts/load-cache.sh
  - bash scripts/start-docker.sh
  - bash scripts/install-drivers-to-docker.sh
  - travis_wait 50 bash scripts/save-cache.sh
  - ls -la docker_cache
  - bash scripts/install-drivers-to-travis.sh

script:
  - npm test

services:
  - docker
