# .travis.yml
language: node_js
dist: xenial
sudo: required

cache:
  directories:
    - "node_modules"
    - "docker_cache"

matrix:
  fast_finish: true
  include:
    - node_js: "10"
    - node_js: "8"

install:
  - npm i

before_script:
  - travis_wait 50 bash scripts/setup-docker.sh

script:
  - npm test

services:
  - docker
